local markov = require("markov")
local str = "This is an example string. This string is delicious. This is an example set of tacos."
local example = markov(str)
for i = 1, 1000 do
  print(example:next())
end
print("--- --- ---")
local strings = {
  "Hello world, this is a test.",
  "I really don't know what I'm doing!",
  "This should be interesting.",
  "I need more variation here.",
  "Hello friends, I'm happy.",
  "I should write more things with more variation in them.",
  "In here is a little world, full of knowledge."
}
local m2 = markov(strings)
math.randomseed(os.time())
for i = 1, 10 do
  print(m2:string())
end
for i = 1, 5 do
  print(m2:string({
    max_length = 3
  }))
end
local elements = {
  "Hydrogen",
  "Helium",
  "Lithium",
  "Beryllium",
  "Boron",
  "Carbon",
  "Nitrogen",
  "Oxygen",
  "Fluorine",
  "Neon",
  "Sodium",
  "Magnesium",
  "Aluminium",
  "Silicon",
  "Phosphorus",
  "Sulfur",
  "Chlorine",
  "Argon",
  "Potassium",
  "Calcium",
  "Scandium",
  "Titanium",
  "Vanadium",
  "Chromium",
  "Manganese",
  "Iron",
  "Cobalt",
  "Nickel",
  "Copper",
  "Zinc",
  "Gallium",
  "Germanium",
  "Arsenic",
  "Selenium",
  "Bromine",
  "Krypton",
  "Rubidium",
  "Strontium",
  "Yttrium",
  "Zirconium",
  "Niobium",
  "Molybdenum",
  "Technetium",
  "Ruthenium",
  "Rhodium",
  "Palladium",
  "Silver",
  "Cadmium",
  "Indium",
  "Tin",
  "Antimony",
  "Tellurium",
  "Iodine",
  "Xenon",
  "Cesium",
  "Barium",
  "Lanthanum",
  "Cerium",
  "Praseodymium",
  "Neodymium",
  "Promethium",
  "Samarium",
  "Europium",
  "Gadolinium",
  "Terbium",
  "Dysprosium",
  "Holmium",
  "Erbium",
  "Thulium",
  "Ytterbium",
  "Lutetium",
  "Hafnium",
  "Tantalum",
  "Tungsten",
  "Rhenium",
  "Osmium",
  "Iridium",
  "Platinum",
  "Gold",
  "Mercury",
  "Thallium",
  "Lead",
  "Bismuth",
  "Polonium",
  "Astatine",
  "Radon",
  "Francium",
  "Radium",
  "Actinium",
  "Thorium",
  "Protactinium",
  "Uranium",
  "Neptunium",
  "Plutonium",
  "Americium",
  "Curium",
  "Berkelium",
  "Californium",
  "Einsteinium",
  "Fermium",
  "Mendelevium",
  "Nobelium",
  "Lawrencium",
  "Rutherfordium",
  "Dubnium",
  "Seaborgium",
  "Bohrium",
  "Hassium",
  "Meitnerium",
  "Darmstadtium",
  "Roentgenium",
  "Copernicium",
  "Nihonium",
  "Flerovium",
  "Moscovium",
  "Livermorium",
  "Tennessine",
  "Oganesson",
  "Ununennium",
  pattern = "%a",
  order = 2
}
local m3 = markov(elements)
print("---")
print("---")
for i = 1, 20 do
  print(m3:string({
    sep = "",
    max_length = 13
  }))
end
print("START = " .. tostring(markov.START))
print("END = " .. tostring(markov.END))
local other_things = {
  "Dilithium",
  "Tritium",
  "Bronze",
  "Protium",
  "Gundanium",
  "Latinum",
  "Tyberium",
  "Quadium",
  "Adamantium",
  "Etherium",
  "Jasmium",
  "Mithril",
  "Xenium",
  "Rearden",
  "Zanium",
  "Marizapan",
  "Segnomin",
  "Docherty",
  "Tedium",
  "Thankium",
  "Geekium",
  "Satisfactium",
  "Alarmose",
  "Cursium",
  "Brainium",
  "Arsole",
  "Adamantane",
  "Bastardane",
  "Fullerene",
  "Putrescine",
  "Cadaverine",
  "Spermine",
  "Arabitol",
  "Fucitol",
  "Vomicine",
  "Gossypol",
  "Skatole",
  "Sparassol",
  "Psicose",
  "Nonanone",
  "Pubescine",
  "Funicone",
  "Housane",
  "Domperidone",
  "Germane",
  "Uranate",
  "Kunzite",
  "Spodumene",
  "Conantokin",
  "Cubane",
  "Anol",
  "Buccalin",
  "Dinile",
  "Fornacite",
  "Butanal",
  "Clitorin",
  "Fucol",
  "Ovalene",
  "Fuchsite",
  "Pagodane",
  "Apatite",
  "Lepidopterene",
  "Snoutene",
  "Cacodyl",
  "Screwene",
  "Furfuryl",
  "Carnallite",
  "Draculin",
  "Toronton",
  "Praesium",
  "Halivalium",
  "Flubber",
  "Axonite",
  "Bolonium",
  "Corbomite",
  "Chronoton",
  "Capsidium",
  "Tylium",
  "Acoustium",
  "Necrogen",
  "Tiberium",
  "Metatron",
  "Chorizite",
  "Phazon",
  "Oxyale",
  "Magicite",
  "Balthazate",
  "Zydrine",
  "Morphite",
  "Tritanium",
  "Nocxium",
  "Elerium",
  "Infernium",
  "Timonium",
  "Neoteutonium",
  "Bendezium",
  "Hellion",
  "Moonsilver",
  "Soulsteel",
  "Orichalcum",
  "Uridium",
  "Psitanium",
  "Zexonite",
  "Sinisite",
  "Tronium",
  "Zfylud",
  "Primium",
  "Jouronium",
  "Runite",
  "Technoorganic",
  "Vibranium",
  "Zuunium",
  "Nucleon",
  "Redstone",
  "Carbonite",
  "Inerton",
  "Xenothium",
  "Energon",
  "Calculon",
  "Eternium",
  "Trioxin",
  "Unobtanium",
  "Elephantanium",
  "Turbidium",
  "Schwartz",
  "Balthorium",
  "Galvorn",
  "Byzantium",
  "Aether",
  "Atium",
  "Australium",
  "Bavarium",
  "Byzanium",
  "Carbonadium",
  "Cavorite",
  "Chlorophyte",
  "Corrodium",
  "Divinium",
  "Duranium",
  "Durium",
  "Feminum",
  "Frinkonium",
  "Harbenite",
  "Lerasium",
  "Meteorillium",
  "Naqahdah",
  "Octiron",
  "Polydenum",
  "Saronite",
  "Saturnium",
  "Scrith",
  "Taydenite",
  "Uru",
  "Verterium",
  "Xirdalium",
  "Xithricite",
  "Quantium",
  "Philosophon",
  "Reson",
  "Tachyon",
  "Thaum",
  "Computronium",
  "Electrum",
  "Neutronium",
  "Nitrium",
  "Trilithium",
  "Kironide",
  "Pergium",
  "Cordrazine",
  "Inaprovaline",
  "Ketracel",
  "Retinax",
  "Archerite",
  pattern = "%a",
  order = 2
}
for i = 1, #elements do
  table.insert(other_things, elements[i])
end
local m4 = markov(other_things)
for i = 1, 20 do
  print(m4:string({
    sep = "",
    max_length = 13
  }))
end
